server_ip = "192.168.56.101"
nodes = {
  "node0" => "192.168.56.110",
  "node1" => "192.168.56.111",
  "node2" => "192.168.56.112"
}

server_provision = <<-SHELL
  apt-get -y --force-yes update
  echo iptables-persistent iptables-persistent/autosave_v4 boolean true | sudo debconf-set-selections
  echo iptables-persistent iptables-persistent/autosave_v6 boolean true | sudo debconf-set-selections
  apt-get install -y wget curl vim tmux openssl git net-tools conntrack iptables-persistent
  export SERVER_IP=#{server_ip}
  export INSTALL_K3S_EXEC="--bind-address=$SERVER_IP --node-external-ip=$SERVER_IP --flannel-iface=eth1"
  curl -sfL https://get.k3s.io | sh -
  echo "let k3s start .."
  sleep 10
  cp /var/lib/rancher/k3s/server/token /vagrant_shared
  cp /etc/rancher/k3s/k3s.yaml /vagrant_shared
  iptables -A INPUT -p tcp --dport 6443 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
  iptables -A OUTPUT -p tcp --sport 6443 -m conntrack --ctstate ESTABLISHED -j ACCEPT
  iptables-save > /etc/iptables/rules.v4
SHELL

node_provision = <<-SHELL
  apt-get -y --force-yes update
  apt-get install -y wget curl vim tmux openssl git net-tools conntrack
  export K3S_TOKEN_FILE=/vagrant_shared/token
  export K3S_URL=https://#{server_ip}:6443
  export INSTALL_K3S_EXEC="--flannel-iface=eth1"
  curl -sfL https://get.k3s.io | sh -
SHELL

Vagrant.configure("2") do |config|
  # controlplane
  config.vm.define "server" do |server|
    server.vm.box = "debian/bookworm64"
    server.vm.disk :disk, size: "20GB", primary: true
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: server_ip
    server.vm.synced_folder "./shared", "/vagrant_shared", type: "virtualbox"
    server.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 2048
      v.cpus = 2
      v.customize [
        "modifyvm", :id,
        "--vram", "23"
      ]
    end
    server.vm.provision "shell", inline: server_provision
  end

  # worker nodes
  nodes.each do |node_name, node_ip|
    config.vm.define node_name do |node|
      node.vm.box = "debian/bookworm64"
      node.vm.disk :disk, size: "10GB", primary: true
      node.vm.hostname = node_name
      node.vm.network "private_network", ip: node_ip
      node.vm.synced_folder "./shared", "/vagrant_shared", type: "virtualbox"
      node.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
      end
      node.vm.provision "shell", inline: node_provision
    end
  end
end

